# Generated by Django 4.0.4 on 2022-06-04 04:34

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[dashboard.validators.file_size], verbose_name='Video location'),
        ),
    ]
