# Generated by Django 4.0.4 on 2022-06-04 05:06

import dashboard.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_video_title_alter_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[dashboard.validators.file_size], verbose_name=''),
        ),
    ]
