# Generated by Django 4.0.4 on 2022-06-04 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_video_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
