# Generated by Django 4.0.4 on 2022-06-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_user_video_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_duration',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
