# Generated by Django 4.0.4 on 2022-06-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_video_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='photos/thumbnails/%Y/%m/%d/'),
        ),
    ]
