# Generated by Django 4.0.4 on 2022-06-18 03:57

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='videos/%Y/%m/%d/', validators=[dashboard.validators.file_size, dashboard.validators.validate_file_extension], verbose_name=''),
        ),
    ]
