# Generated by Django 4.0.4 on 2022-06-24 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_video_video_frames_alter_video_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_duration',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_frames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), null=True, size=None),
        ),
    ]
